### PR TITLE
Broken links in README

### PR DESCRIPTION
**Pull request by 0fie**

### CODE REVIEW

**Comment by elythh** [comment]
It adds neoscroll back haha, I removed that commit tho

**Comment by elythh** [comment]
80d536031a6a3394e5277845e98bb6bd11d0143a instead

**Comment by 0fie** [comment]
awesome! I don't understand why it was adding Neoscroll though. 😆

**Comment by elythh** [comment]
you probably forked before I deleted my commit, happens I love rewriting my git tree

**Comment by 0fie** [comment]
Understood. I will get used to it :)

**Pull request closed without merging**
